version: 1
root:
  handlers: ["stdout", "file"]
  level: DEBUG
handlers:
  stdout:
    formatter: standard
    class: logging.StreamHandler
    level: DEBUG
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: standard
    filename: ./logs/mqtt-to-graphite.log
    maxBytes: 1024000
    backupCount: 3
formatters:
  standard:
    format: "%(levelname)-8s | %(asctime)s | %(threadName)-25s | %(name)s: %(message)s"
